# =============================================
# CONFIGURAÇÕES DO BANCO DE DADOS (PRODUÇÃO)
# =============================================
# Conexão via variáveis de ambiente para segurança
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =============================================
# CONFIGURAÇÕES JPA / HIBERNATE (PRODUÇÃO)
# =============================================
# 'none' para evitar que o Hibernate modifique o schema do banco acidentalmente
spring.jpa.hibernate.ddl-auto=none

# Dialeto específico do banco de produção
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Desabilitar logs SQL para nãoo poluir os logs e melhorar a performance
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =============================================
# SEGURANÇA (JWT)
# =============================================
# Chave secreta via variável de ambiente para segurança
jwt.secret=${JWT_SECRET}

# Expiração do token para Lojista (12 horas)
jwt.lojista.expiration=43200000

# Expiração do token para Consumidor (1 hora)
jwt.consumidor.expiration=3600000

# =============================================
# UPLOAD DE ARQUIVOS
# =============================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# =============================================
# CONFIGURAÇÃO CORS (PRODUÇÃO)
# =============================================
# Define as origens permitidas via vari�vel de ambiente.
# Ex: "https://meusite.com,https://meuapp.com"
cors.origins=${CORS_ORIGINS}

# =============================================
# VERSÃO DE DISTRIBUIÇÃO (Doisv/Logvert)
# =============================================
app.distribuicao.ativa=${APP_DISTRIBUICAO}

# =============================================
# CONFIGURAÇÃO ENVIO DE EMAIL (PRODUÇÃO)
# =============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Use variáveis de ambiente para credenciais, especialmente a senha.
spring.mail.username=${MAIL_USERNAME:logistica.doisv@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =============================================
# DOMINIOS DA APLICA��O
# =============================================
app.dominio.email = ${DOMINIO_EMAIL}
app.dominio.cnpj = ${DOMINIO_CNPJ}