# Conexão com banco de dados MySQL
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Dialeto do banco
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Logs SQL (opcional na produção, pode remover para evitar excesso de log)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Chave de segurança
jwt.secret=${CHAVE_SEGURANCA}

# Limite para upload de arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
